In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
df = pd.read_csv('DataCoSupplyChainDataset.csv', encoding='ISO-8859-1')
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)


df['order date (DateOrders)'] = pd.to_datetime(df['order date (DateOrders)'])
df['shipping date (DateOrders)'] = pd.to_datetime(df['shipping date (DateOrders)'])


columns_to_drop = [
    # PII / no analytical value
    'Customer Email',
    'Customer Password',
    'Customer Fname',
    'Customer Lname',
    'Customer Street',

    # Empty or near-useless
    'Product Description',      # 100% missing
    'Product Image',            # just a URL
    'Order Zipcode',            # ~86% missing
    'Product Status',            # ~99% missing
    # Redundant duplicate IDs
    'Order Customer Id',        # duplicate of Customer Id
    'Product Category Id',      # duplicate of Category Id
    'Order Item Cardprod Id',   # duplicate of Product Card Id
]
df_clean = df.drop(columns=columns_to_drop)

df_clean = df_clean.rename(columns={'shipping date (DateOrders)': 'Shipping_Date', 
                                    'order date (DateOrders)': 'Order_Date',
                                    'Days for shipping (real)' : 'Shipping_days',
                                    'Days for shipment (scheduled)' : 'Scheduled_shipping_days', 
                                    'Order Profit Per Order' : 'Profit_per_order',
                                      'Order Item Discount Rate' : 'Discount_rate', 
                                      'Order Item Profit Ratio' : 'Profit_ratio',
                                      'Order Item Quantity' : 'Quantity',
                                      'Order Item Product Price' : 'Prroduct_price',
                                      'Order Item Discount' : 'Discount',
                                      'Order Item Total' : 'Order_item_total',
                                      'Shipping Mode' : 'Shipping_mode',
                                      'Order Region' : 'Order_region',
                                      'Order State': 'Order_state',
                                      'Order Status' : 'Order_status'})   #Renaming columns

df_clean = df_clean.fillna({'Customer Zipcode': '00000'})   #Replacing values in customer zipcode with '00000'

In [2]:
category_summary = (
    df_clean
    .groupby('Category Name')
    .agg(
        Total_sales=('Sales', 'sum'),
        Total_profit=('Profit_per_order', 'sum')
    )
    .round(2)
    .reset_index()
)

category_summary['profit_margin'] = (category_summary['Total_profit'] / category_summary['Total_sales']).round(3)
category_summary = category_summary.sort_values(by='Total_sales', ascending= False).reset_index(drop=True)

category_summary.head(10)

          Category Name  Total_sales  Total_profit  profit_margin
0               Fishing   6929653.69     756220.77          0.109
1                Cleats   4431942.78     494636.92          0.112
2      Camping & Hiking   4118425.57     427455.57          0.104
3      Cardio Equipment   3694843.20     383011.10          0.104
4       Women's Apparel   3147800.00     350421.03          0.111
5          Water Sports   3113844.68     325146.96          0.104
6        Men's Footwear   2891757.66     311902.82          0.108
7  Indoor/Outdoor Games   2888993.91     318451.43          0.110
8         Shop By Sport   1309522.04     129813.96          0.099
9             Computers    663000.00      69656.81          0.105

In [3]:

category_summary.sort_values(by='Total_sales', ascending=True).head(5).reset_index(drop=True)

       Category Name  Total_sales  Total_profit  profit_margin
0               CDs       3059.59        383.85          0.125
1               Toys      6104.66        900.71          0.148
2  Golf Bags & Carts     10369.39       1810.07          0.175
3              Baby      12229.56       1525.03          0.125
4             Books      12587.40        883.01          0.070

In [4]:

category_summary.sort_values(by='profit_margin', ascending=False).head(5).reset_index(drop=True)

         Category Name  Total_sales  Total_profit  profit_margin
0    Golf Bags & Carts     10369.39       1810.07          0.175
1  Fitness Accessories     35601.44       5258.39          0.148
2                 Toys      6104.66        900.71          0.148
3               Soccer     26477.05       3901.95          0.147
4     Women's Clothing    140283.00      19102.85          0.136

In [5]:
category_summary.sort_values(by='profit_margin', ascending=False).head(5).reset_index(drop=True)

         Category Name  Total_sales  Total_profit  profit_margin
0    Golf Bags & Carts     10369.39       1810.07          0.175
1  Fitness Accessories     35601.44       5258.39          0.148
2                 Toys      6104.66        900.71          0.148
3               Soccer     26477.05       3901.95          0.147
4     Women's Clothing    140283.00      19102.85          0.136